### ISSUE TITLE
Can you add LICENSE file?

### ISSUE THREAD

**Issue by ktanakaj** [crazybooot/base64-validation#1]
Hi! I'm finding a base64 validation library for Laravel.
I found your library and it can be worked with my app.

However there are no licenses. I can use only OSS libraries.
Can you add following license information and rerelease the library?

* `LICENSE.txt` file (https://help.github.com/articles/licensing-a-repository/)
* License section in `README.md`
* `license` field in `composer.json` (https://getcomposer.org/doc/04-schema.md#license)

**Comment by crazybooot** [comment]
Added MIT license

**Comment by ktanakaj** [comment]
Thank you very much for your quick response! :blush:
