### ISSUE TITLE
Increasing tmp directory size

### ISSUE THREAD

**Issue by renjithspace** [crazybooot/base64-validation#11]
https://github.com/crazybooot/base64-validation/blob/c5d00aac597acf0e15e4c1238f476f5a72a4110d/src/Validators/Base64Validator.php#L174
<img width="1008" alt="Screenshot 2020-04-22 at 2 46 51 PM" src="https://user-images.githubusercontent.com/11629673/79964338-2a767580-84a8-11ea-94a9-ba5a12f6332f.png">

**Comment by uttamrabadiya** [comment]
Issue isn't fixed yet. tmp file is not getting deleted after validation.
