### ISSUE TITLE
Validation: base64dimensions:min_width=100,min_height=200

### ISSUE THREAD

**Issue by bennyvanvracem1984** [crazybooot/base64-validation#2]
only the validation: base64dimensions:min_width=100,min_height=200 is not working: 
i get this error

Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Symfony\Component\HttpFoundation\File\File::getClientMimeType() in file /vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php on line 491

laravel version 5,7,28

**Comment by PepijnDeWachter** [comment]
hi, I have resolved this issue in my fork of this, feel free to use it: https://github.com/PepijnDeWachter/base64-validation
you'll have to manually add the repository to your composer since I have not registered it on packagist, instructions on how to do that can be found on google

**Comment by crazybooot** [comment]
fixed

**Comment by crazybooot** [comment]
@PepijnDeWachter thank you for idea how to fix this issue. Next time you can make pull request with bug fixes.

**Comment by PepijnDeWachter** [comment]
> @PepijnDeWachter thank you for idea how to fix this issue. Next time you can make pull request with bug fixes.

I agree that a pull request is the better option for this, but I falsely assumed from the complete lack of activity on this repo that it was not maintained, so I decided to fork it to immediately fix my problem which was happening in a production environment.
I do want to add that in the commit you did you only added the overridden method, but as far as I can see the code still calls the $validator instance passed in the signature of the method, which doesn't inherit the method (it's line 67), I also failed to initially notice this and patched it in https://github.com/PepijnDeWachter/base64-validation/commit/bbbdc14e18dbd6954e226fd9d417d713a3361617 (seems to small of a change to make a pull request for in my opinion, but opinions might vary) if you would add that fix and tag a new version I'll probably remove my fork as it would be obsolete then.

I'll remember now that this repo isn't dead ;)

**Comment by crazybooot** [comment]
@PepijnDeWachter you are absolutely right. Thank you for notice. I completely fixed this issue in my last commit.

**Comment by PepijnDeWachter** [comment]
No problem, this package is a godsent for our laravel api's using base64 for file uploads, it would be great if you could tag a new release when you find the time, since using commit tags in composer isn't considered a good practice (though I have had to do it in production multiple times)
Thank you for creating this
