### ISSUE TITLE
Laravel 9 Compatibility

### ISSUE THREAD

**Issue by mikkoaf** [crazybooot/base64-validation#23]
There are the following dependency issues:
```
$ composer why-not laravel/framework "^9.0"
crazybooot/base64-validation               1.0.9     requires          laravel/framework (^5.5|^6.0|^7.0|^8.0)
```

**Comment by MichielVervaart** [comment]
Good morning,

Would be nice if this was updated to Laravel 9, so we can update without workarounds :)

**Comment by mikkoaf** [comment]
This issue was closed with https://github.com/crazybooot/base64-validation/pull/25
