### ISSUE TITLE
Validation Messages

### ISSUE THREAD

**Issue by Foohx** [crazybooot/base64-validation#5]
Hi,

I'm using your validation package in **FormRequest** and I need to override error messages for some rules. 

In a **FormRequest** class I have something like

```php
	public function rules()
	{
		return [
			'picture' => 'base64image|base64max:1000', // 1MB
		];
	}
	
	public function messages()
	{
		return [
			'picture.image' => "Custom Err 1",
			'picture.max' => "Custom Err 2",
			'picture.base64image' => "Custom Err 3",
			'picture.base64max' => "Custom Err 4",
		];
	}
```

But nothing work and I'm always getting this kind of messages `The picture may not be greater than 1000 kilobytes.` instead of `Custom Err X`

Thanks for your help
Foohx

**Comment by crazybooot** [comment]
I have just added solution for message localization, you can find instructions here https://github.com/crazybooot/base64-validation/tree/1.0.3#localization
Thank you for feedback!

**Comment by Foohx** [comment]
Perfect, it works 🥇

**Comment by Foohx** [comment]
Thanks
