### ISSUE TITLE
Unhandled Exception in validator

### ISSUE THREAD

**Issue by EcoFreak** [crazybooot/base64-validation#6]
I'm using these validation rules (great btw!) and found a possible problem.

**With this request rules**

```
public function rules()
{
        return [
            'signature' => 'base64image|required'
        ];
}
```

If the request contains a signature field as a string all the validations work ok but if the request has the signature field has a file (uploaded as form-data) it triggers and the following exception.

**Details**

`
Argument 1 passed to Crazybooot\\Base64Validation\\Validators\\Base64Validator::convertToFile() must be of the type string, object given, called in D:\\Users\\henrique.g.ferreira\\PhpstormProjects\\webpm-api\\vendor\\crazybooot\\base64-validation\\src\\Validators\\Base64Validator.php on line 97"
`

Thanks

**Comment by johnnykatz** [comment]
could you solve somehow?
